Верстка страницы Каталог и Форма
htmlacademy-adaptive/1450419-cat-energy-24 pull request #3
Opened 2021-12-04 08:33 UTC by kivals

2021-12-04 19:21 UTC, mouxez requested changes

2021-12-04 19:21 UTC, mouxez commented on source/catalog.html
> +    <section class="catalog catalog__wrapper">
catalog__wrapper не нужен
для чего его используешь?
все свойства стилевые вполне можно положить в класс catalog

2021-12-04 19:21 UTC, mouxez commented on source/catalog.html
> +          <li class="extra__item extra-item">
?

2021-12-04 19:21 UTC, mouxez commented on source/catalog.html
> +          <li class="extra__item extra-item">
extra__item extra-item

2021-12-04 19:21 UTC, mouxez commented on source/catalog.html
> +    <section class="cooperate cooperate__wrapper">
тут достаточно класса cooperate

2021-12-04 19:21 UTC, mouxez commented on source/catalog.html
> +          <li class="extra__item extra-item">
наверно стоит просмотреть проект и избавиться от двойных названий
на данном этапе (до стилизации) не стоит указывать по несколько классов, так как не факт что они понадобятся

2021-12-04 19:21 UTC, mouxez commented on source/form.html
> +    <section class="send send__wrapper">
в этом файле также надо по максимуму избавиться от двойных классов

2021-12-04 19:54 UTC, mouxez commented
самое главное - в ветке module2-task2 отсутствует страница index.html
точнее она есть но без кода.
надо это исправить
получилось так, что ты создал ветку module2-task2 не обновив мастер своего форка скорее всего
в любом случае надо подтянуть изменения в эту ветку

2021-12-06 08:10 UTC, kivals commented on source/catalog.html
> +          <li class="extra__item extra-item">
Подчистил. Использовал миксы. extra__item - для стилизации внешних отступов. extra-item - стилизация блока. Вероятно что не нужны будут.

2021-12-06 16:30 UTC, merged