Подключение sass модулей и начало верстки.
htmlacademy-adaptive/1450419-cat-energy-24 pull request #4
Opened 2021-12-07 10:29 UTC by kivals

2021-12-07 18:42 UTC, mouxez requested changes

2021-12-07 18:42 UTC, mouxez commented on source/catalog.html
>  <body class="page__body">
тут не подходит class="page__body"
так как через _ показывается элемент, а блока получается что нет
нужно название без _

2021-12-07 18:42 UTC, mouxez commented on source/sass/catalog-item.scss
> +.catalog-item {
по хорошему надо найти возможность объединить catalog и catalog-item

2021-12-07 18:42 UTC, mouxez commented on source/sass/catalog-item.scss
> +.catalog-item {
правильно понимаю, что catalog-item это элемент catalog?
если да, то нужно переосмыслить именование и поместить всё в один файл

2021-12-07 18:42 UTC, mouxez commented on source/sass/extra.scss
> +.extra__title {
тоже самое, как в catalog

2021-12-07 18:42 UTC, mouxez commented on source/sass/layout/page-body.scss
> +.page-body {
тут у тебя используется класс .page-body, а в разметке .page_body
замени в разметке на .page-body и всё будет ок.
сейчас эти стили не применяются. надо всегда проверять применились стили или нет

2021-12-07 18:42 UTC, mouxez commented on source/sass/style.scss
> +@import "common/mixins";
первым должен быть импорт variables, затем шрифты и после миксины
подумай почему так

2021-12-07 18:42 UTC, mouxez commented on source/sass/style.scss
>  // Начните писать стили здесь
?

2021-12-07 18:42 UTC, mouxez commented on source/sass/ui/button.scss
> +.button {
отдельным тэгам создавать файлы не надо. если есть общие для тэгов стили их надо положить в global.scss

2021-12-07 18:42 UTC, mouxez commented on source/sass/ui/input.scss
> +.input {
global.scss

2021-12-07 18:42 UTC, mouxez commented on source/sass/ui/textarea.scss
> +.textarea {
global

2021-12-07 18:42 UTC, mouxez commented on source/sass/ui/section-title.scss
> +.section-title {
тут название файла должно быть section

2021-12-08 07:06 UTC, kivals commented on source/catalog.html
>  <body class="page__body">
Согласен. Но такое увидел в верстке "Барбершоп. Адаптивная сетка статистики" во время лайва.

2021-12-08 08:29 UTC, kivals commented on source/sass/ui/section-title.scss
> +.section-title {
Это отдельный блок. Так rfr на сайте есть однотипные заголовки. У них класс section-title

2021-12-08 13:22 UTC, merged